In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
%cd /content/drive/MyDrive/국토교통부

/content/drive/MyDrive/국토교통부

In [6]:
import pandas as pd

In [3]:
send = [['강남구', 1_906_553, 2_140_187, 2_340_527, 2_129_089, 69_427],
        ['강동구', 613_974, 725_903, 712_541, 684_139, 22_309],
        ['강북구', 463_450, 525_812, 478_381, 489_214, 15_953],
        ['강서구', 1_913_266, 2_219_659, 2_180_487, 2_104_471, 68_624],
        ['관악구', 511_945, 615_135, 613_539, 580_206, 18_920],
        ['광진구', 752_355, 849_956, 888_628, 830_313, 27_075],
        ['구로구', 820_675, 912_984, 979_649, 904_436, 29_492],
        ['금천구', 1_892_209, 2_000_072, 1_899_967, 1_930_749, 62_959],
        ['노원구', 590_481, 655_340, 622_290, 622_704, 20_306],
        ['도봉구', 709_438, 770_334, 718_909, 732_894, 23_899],
        ['동대문구', 1_113_456, 1_262_658, 1_224_275, 1_200_130, 39_135],
        ['동작구', 541_753, 551_994, 565_257, 553_001, 18_033],
        ['마포구', 1_473_139, 1_959_310, 1_825_241, 1_752_563, 57_149],
        ['서대문구', 419_093, 510_722, 533_650, 487_822, 15_907],
        ['서초구', 851_510, 912_081, 1_058_731, 940_774, 30_677],
        ['성동구', 1_476_095, 1_524_306, 1_455_893, 1_485_431, 48_438],
        ['성북구', 2_058_338, 2_300_768, 2_275_704, 2_211_603, 72_118],
        ['송파구', 2_340_553, 2_428_974, 2_626_830, 2_465_452, 80_395],
        ['양천구', 562_422, 652_303, 709_810, 641_512, 20_919],
        ['영등포구', 1_018_915, 1_166_978, 1_180_992, 1_122_295, 36_597],
        ['용산구', 1_124_541, 1_292_160, 1_396_944, 1_271_215, 41_453],
        ['은평구', 486_603, 582_226, 545_974, 538_268, 17_552],
        ['종로구', 715_004, 780_950, 791_135, 762_363, 24_860],
        ['중구', 1_166_807, 1_243_433, 1_190_651, 1_200_297, 39_140],
        ['중랑구', 934_335, 1_064_676, 1_094_849, 1_031_287, 33_629]]

In [8]:
send_pd = pd.DataFrame(send, columns=['구분', '10월', '11월', '12월', '월 평균', '일 평균'])
send_pd

      구분      10월      11월      12월     월 평균   일 평균
0    강남구  1906553  2140187  2340527  2129089  69427
1    강동구   613974   725903   712541   684139  22309
2    강북구   463450   525812   478381   489214  15953
3    강서구  1913266  2219659  2180487  2104471  68624
4    관악구   511945   615135   613539   580206  18920
5    광진구   752355   849956   888628   830313  27075
6    구로구   820675   912984   979649   904436  29492
7    금천구  1892209  2000072  1899967  1930749  62959
8    노원구   590481   655340   622290   622704  20306
9    도봉구   709438   770334   718909   732894  23899
10  동대문구  1113456  1262658  1224275  1200130  39135
11   동작구   541753   551994   565257   553001  18033
12   마포구  1473139  1959310  1825241  1752563  57149
13  서대문구   419093   510722   533650   487822  15907
14   서초구   851510   912081  1058731   940774  30677
15   성동구  1476095  1524306  1455893  1485431  48438
16   성북구  2058338  2300768  2275704  2211603  72118
17   송파구  2340553  2428974  2626830  2465452  80395
18   양천구   562422   652303   709810   641512  20919
19  영등포구  1018915  1166978  1180992  1122295  36597
20   용산구  1124541  1292160  1396944  1271215  41453
21   은평구   486603   582226   545974   538268  17552
22   종로구   715004   780950   791135   762363  24860
23    중구  1166807  1243433  1190651  1200297  39140
24   중랑구   934335  1064676  1094849  1031287  33629

In [5]:
receive = [['강남구', 2_096_274, 2_355_919, 2_411_797, 2_287_997, 74_609],
           ['강동구', 1_153_240, 1_308_600, 1_314_334, 1_258_725, 41_045],
           ['강북구', 676_537, 770_054, 760_443, 735_678, 23_990],
           ['강서구', 1_676_638, 1_917_028, 1_914_856, 1_836_174, 59_875],
           ['관악구', 1_334_478, 1_504_104, 1_492_038, 1_443_540, 47_072],
           ['광진구', 967_922, 1_086_427, 1_088_197, 1_047_515, 34_158],
           ['구로구', 1_058_351, 1_216_298, 1_229_996, 1_168_215, 38_094],
           ['금천구', 812_839, 897_304, 889_541, 866_561, 28_257],
           ['노원구', 1_232_720, 1_397_611, 1_380_335, 1_336_889, 43_594],
           ['도봉구', 719_889, 821_272, 810_817, 783_993, 25_565],
           ['동대문구', 930_627, 1_051_519, 1_049_928, 1_010_691, 32_957],
           ['동작구', 1_020_371, 1_156_297, 1_151_930, 1_109_533, 36_180],
           ['마포구', 1_213_652, 1_379_913, 1_408_260, 1_333_942, 43_498],
           ['서대문구', 838_594, 947_953, 944_260, 910_269, 29_683],
           ['서초구', 1_415_295, 1_596_887, 1_630_603, 1_547_595, 50_465],
           ['성동구', 1_000_105, 1_126_383, 1_153_840, 1_093_443, 35_656],
           ['성북구', 1_141_843, 1_290_333, 1_284_411, 1_238_862, 40_398],
           ['송파구', 1_907_308, 2_162_363, 2_174_255, 2_081_309, 67_869],
           ['양천구', 1_092_138, 1_236_814, 1_222_601, 1_183_851, 38_604],
           ['영등포구', 1_157_009, 1_322_541, 1_341_374, 1_273_641, 41_532],
           ['용산구', 718_925, 821_142, 837_232, 792_433, 25_840],
           ['은평구', 1_096_644, 1_248_284, 1_244_594, 1_196_507, 39_017],
           ['종로구', 462_206, 528_818, 533_868, 508_297, 16_575],
           ['중구', 630_455, 711_150, 716_457, 686_021, 22_370],
           ['중랑구', 890_363, 1_005_534, 1_000_568, 965_488, 31_483]]

In [9]:
receive_pd = pd.DataFrame(receive, columns=['구분', '10월', '11월', '12월', '월 평균', '일 평균'])
receive_pd

      구분      10월      11월      12월     월 평균   일 평균
0    강남구  2096274  2355919  2411797  2287997  74609
1    강동구  1153240  1308600  1314334  1258725  41045
2    강북구   676537   770054   760443   735678  23990
3    강서구  1676638  1917028  1914856  1836174  59875
4    관악구  1334478  1504104  1492038  1443540  47072
5    광진구   967922  1086427  1088197  1047515  34158
6    구로구  1058351  1216298  1229996  1168215  38094
7    금천구   812839   897304   889541   866561  28257
8    노원구  1232720  1397611  1380335  1336889  43594
9    도봉구   719889   821272   810817   783993  25565
10  동대문구   930627  1051519  1049928  1010691  32957
11   동작구  1020371  1156297  1151930  1109533  36180
12   마포구  1213652  1379913  1408260  1333942  43498
13  서대문구   838594   947953   944260   910269  29683
14   서초구  1415295  1596887  1630603  1547595  50465
15   성동구  1000105  1126383  1153840  1093443  35656
16   성북구  1141843  1290333  1284411  1238862  40398
17   송파구  1907308  2162363  2174255  2081309  67869
18   양천구  1092138  1236814  1222601  1183851  38604
19  영등포구  1157009  1322541  1341374  1273641  41532
20   용산구   718925   821142   837232   792433  25840
21   은평구  1096644  1248284  1244594  1196507  39017
22   종로구   462206   528818   533868   508297  16575
23    중구   630455   711150   716457   686021  22370
24   중랑구   890363  1005534  1000568   965488  31483

In [13]:
send_pd.to_csv('택배발생량.csv', index=False)
receive_pd.to_csv('택배도착량.csv', index=False)

In [15]:
send_pd.sort_values(by='월 평균', ascending=False)

      구분      10월      11월      12월     월 평균   일 평균
17   송파구  2340553  2428974  2626830  2465452  80395
16   성북구  2058338  2300768  2275704  2211603  72118
0    강남구  1906553  2140187  2340527  2129089  69427
3    강서구  1913266  2219659  2180487  2104471  68624
7    금천구  1892209  2000072  1899967  1930749  62959
12   마포구  1473139  1959310  1825241  1752563  57149
15   성동구  1476095  1524306  1455893  1485431  48438
20   용산구  1124541  1292160  1396944  1271215  41453
23    중구  1166807  1243433  1190651  1200297  39140
10  동대문구  1113456  1262658  1224275  1200130  39135
19  영등포구  1018915  1166978  1180992  1122295  36597
24   중랑구   934335  1064676  1094849  1031287  33629
14   서초구   851510   912081  1058731   940774  30677
6    구로구   820675   912984   979649   904436  29492
5    광진구   752355   849956   888628   830313  27075
22   종로구   715004   780950   791135   762363  24860
9    도봉구   709438   770334   718909   732894  23899
1    강동구   613974   725903   712541   684139  22309
18   양천구   562422   652303   709810   641512  20919
8    노원구   590481   655340   622290   622704  20306
4    관악구   511945   615135   613539   580206  18920
11   동작구   541753   551994   565257   553001  18033
21   은평구   486603   582226   545974   538268  17552
2    강북구   463450   525812   478381   489214  15953
13  서대문구   419093   510722   533650   487822  15907